project_id = "ccmxitxgyznethanixlg"

[functions.generate-invoice]
verify_jwt = false

[functions.admin-create-customer]
verify_jwt = false

[functions.confirm-reservation]
verify_jwt = false

[functions.generate-offer]
verify_jwt = false

[functions.accept-offer]
verify_jwt = false

[functions.delete-customer]
verify_jwt = false

[functions.notify-device-return]
verify_jwt = false
