// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-locations.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var LOCATIONS = [
  {
    id: "krefeld",
    name: "Krefeld (Hauptsitz)",
    address: "Anrather Stra\xDFe 291, 47807 Krefeld-Fichtenhain",
    phone: "02151 417 99 04",
    email: "krefeld@slt-rental.de",
    hours: "Mo\u2013Fr 08:00\u201318:00, Sa 10:00\u201314:30 (nach Buchung)",
    url: "https://www.slt-rental.de/standorte/krefeld"
  },
  {
    id: "bonn",
    name: "Bonn",
    address: "Bonn (siehe Website f\xFCr vollst\xE4ndige Adresse)",
    phone: "0228 \u2013 siehe Website",
    email: "bonn@slt-rental.de",
    hours: "Mo\u2013Fr 07:00\u201318:00, Sa 08:00\u201317:30",
    url: "https://www.slt-rental.de/standorte/bonn"
  },
  {
    id: "muelheim",
    name: "M\xFClheim an der Ruhr",
    address: "M\xFClheim an der Ruhr",
    phone: "siehe Website",
    email: "muelheim@slt-rental.de",
    hours: "siehe Website",
    url: "https://www.slt-rental.de/standorte/muelheim"
  }
];
var list_locations_default = defineTool({
  name: "list_locations",
  title: "Standorte auflisten",
  description: "Liefert alle SLT Rental Standorte (Krefeld, Bonn, M\xFClheim an der Ruhr) mit Adresse, Telefon, E-Mail und \xD6ffnungszeiten.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(LOCATIONS, null, 2) }],
    structuredContent: { locations: LOCATIONS }
  })
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var CATEGORIES = [
  { id: "erdbewegung", name: "Minibagger & Erdbewegung" },
  { id: "verdichtung", name: "Verdichtung" },
  { id: "anhaenger", name: "Anh\xE4nger" },
  { id: "hebebuehne", name: "Hebeb\xFChnen & Arbeitsb\xFChnen" },
  { id: "aggregat", name: "Stromaggregate" },
  { id: "heizung", name: "Heizung & Klima" },
  { id: "beleuchtung", name: "Beleuchtung" },
  { id: "beschallung", name: "Beschallung & DJ" },
  { id: "spezialeffekte", name: "Spezialeffekte (Sparkular, Nebel)" },
  { id: "moebel-zelte", name: "M\xF6bel & Zelte" },
  { id: "geschirr-glaeser-besteck", name: "Geschirr, Gl\xE4ser & Besteck" },
  { id: "huepfburg", name: "H\xFCpfburgen" },
  { id: "absperrgitter", name: "Absperrgitter" },
  { id: "werkzeug", name: "Werkzeug" },
  { id: "gartenpflege", name: "Gartenpflege" },
  { id: "nutzfahrzeuge", name: "Nutzfahrzeuge" }
];
var list_categories_default = defineTool2({
  name: "list_categories",
  title: "Mietkategorien auflisten",
  description: "Liefert die Hauptkategorien des SLT Rental Mietportfolios (Bau, Event, Transport) mit Slug und Anzeigename.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(CATEGORIES, null, 2) }],
    structuredContent: { categories: CATEGORIES }
  })
});

// src/lib/mcp/tools/get-category-url.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var VALID_LOCATIONS = ["krefeld", "bonn", "muelheim"];
var get_category_url_default = defineTool3({
  name: "get_category_url",
  title: "Kategorie-URL f\xFCr Standort erzeugen",
  description: "Baut die kanonische URL f\xFCr eine Kategorie an einem Standort, z. B. /mieten/krefeld/anhaenger/. Nutze list_locations und list_categories, um g\xFCltige Slugs zu finden.",
  inputSchema: {
    locationId: z.enum(VALID_LOCATIONS).describe("Standort-Slug: krefeld, bonn oder muelheim."),
    categoryId: z.string().min(1).describe("Kategorie-Slug, z. B. 'anhaenger', 'beschallung', 'moebel-zelte'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ locationId, categoryId }) => {
    const url = `https://www.slt-rental.de/mieten/${locationId}/${categoryId}/`;
    return {
      content: [{ type: "text", text: url }],
      structuredContent: { url, locationId, categoryId }
    };
  }
});

// src/lib/mcp/tools/search-website.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var search_website_default = defineTool4({
  name: "search_website",
  title: "SLT Rental Website durchsuchen",
  description: "F\xFChrt eine Google-Site-Suche auf slt-rental.de aus und liefert die Ergebnis-URL. Nutze dies, um Produkte, Ratgeber oder Landingpages zu finden.",
  inputSchema: {
    query: z2.string().min(2).describe("Suchbegriff, z. B. 'Minibagger 1.8t Krefeld'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: ({ query }) => {
    const url = `https://www.google.com/search?q=${encodeURIComponent(
      `site:slt-rental.de ${query}`
    )}`;
    return {
      content: [{ type: "text", text: url }],
      structuredContent: { searchUrl: url, query }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "slt-rental-mcp",
  title: "SLT Rental",
  version: "0.1.0",
  instructions: "Tools f\xFCr den Baumaschinen- und Eventtechnik-Vermieter SLT Rental (Standorte Krefeld, Bonn, M\xFClheim an der Ruhr). Nutze list_locations und list_categories, um Slugs zu finden, get_category_url f\xFCr Deep-Links in den Mietkatalog und search_website f\xFCr die Volltextsuche auf slt-rental.de. F\xFCr konkrete Angebote verweise auf die Standort-E-Mails (krefeld@ / bonn@ / muelheim@slt-rental.de) oder die Anfrageformulare auf der Website.",
  tools: [list_locations_default, list_categories_default, get_category_url_default, search_website_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
