UPDATE public.b2b_managed_products SET
 slug='slt-eiswuerfelmaschine-profi-45kg',
 name='SLT Eiswürfelmaschine Profi – 45 kg/24 h Edelstahl',
 model_name='Profi-Modell 45 kg/Tag – für Gastronomie, Bar & Großevents',
 description='Gastro-Eiswürfelmaschine mit 45 kg Eis pro 24 h – 45 Würfel je Zyklus in 8 bis 18 Minuten, 28,4 l Vorratsbehälter, Edelstahl, LED-Display, Selbstreinigung.',
 detailed_description='Die große Profi-Variante unserer Eiswürfelmaschinen zum Mieten ist auf den Dauerbetrieb in Gastronomie, Catering, Bar- und Eventbetrieb ausgelegt. Sie produziert bis zu 45 kg Eiswürfel in 24 Stunden; pro Zyklus entstehen 45 Würfel in 8 bis 18 Minuten. Damit versorgt ein einziges Gerät mehrere Cocktail-Stationen und Ausschankpunkte gleichzeitig.

Der Vorratsbehälter fasst 28,4 Liter und damit rund 15 kg Eiswürfel; ein Sichtfenster zeigt den Füllstand auf einen Blick. Die Würfelgröße lässt sich am LED-Display mit Multi-Touch-Bedienfeld wählen, ein einstellbarer Timer startet die Produktion vorab. Eine automatische Selbstreinigungsfunktion hält die Anlage hygienisch, ohne den Betrieb zu unterbrechen. Alle Materialien im Eiskontakt sind geschmacks- und geruchsneutral, das Gehäuse besteht aus Edelstahl.

Der industrielle Pumpenkreislauf arbeitet mit festem Wasseranschluss; Zu- und Ablaufschlauch sind im Lieferumfang enthalten. Die Kompressorleistung beträgt 370 W bei 220–240 V und 50/60 Hz, als Kältemittel kommt R290 zum Einsatz. Höhenverstellbare Standfüße gleichen unebene Untergründe aus, das Netzkabel ist 1,8 m lang.

Das Gerät misst 80 x 40 x 50 cm (H x B x T) bei 25,5 kg Eigengewicht und passt damit unter viele Tresen und auf jede stabile Arbeitsfläche. Verfügbar über die Standorte Krefeld und Bonn – wir prüfen die Verfügbarkeit für deinen Zeitraum und melden uns kurzfristig mit einem Angebot zurück.',
 available_locations=ARRAY['krefeld','bonn']::text[],
 images=ARRAY['/product-images/geschirr/slt-eiswuerfelmaschine-profi-45kg-1.jpeg','/product-images/geschirr/slt-eiswuerfelmaschine-profi-45kg-2.jpeg']::text[],
 image_alts=ARRAY['Profi-Eiswürfelmaschine mieten – Edelstahlgerät mit Sichtfenster und LED-Bedienfeld','Eiswürfelmaschine 45 kg mieten – Abmessungen 80 x 40 x 50 cm sowie Eisschaufel, Zulauf- und Ablaufschlauch']::text[],
 specifications='{"Geräteart":"Gastro-Eiswürfelbereiter, freistehend / Untertheken-Aufstellung","Material":"Edelstahlgehäuse","Tageskapazität":"45 kg Eiswürfel in 24 Stunden","Zyklusleistung":"45 Eiswürfel je Zyklus","Zyklusdauer":"8 bis 18 Minuten","Vorratsbehälter":"28,4 Liter (ca. 15 kg Eiswürfel)","Würfelgröße":"Wählbar über LED-Bedienfeld","Bedienung":"LED-Display mit Multi-Touch-Bedienfeld und einstellbarem Timer","Reinigung":"Automatische Selbstreinigungsfunktion","Wasserversorgung":"Industrieller Pumpenkreislauf mit festem Wasseranschluss, Zu- und Ablaufschlauch im Lieferumfang","Leistung":"370 W","Spannung":"220–240 V, 50/60 Hz","Kältemittel":"R290","Abmessungen":"80 x 40 x 50 cm (H x B x T)","Gewicht":"25,5 kg","Netzkabellänge":"1,8 m","Standfüße":"Höhenverstellbar","Einsatzbereich":"Bars, Restaurants, Cafés, Hotels, Cateringbetriebe, Events"}'::jsonb,
 features=ARRAY['45 kg Eiswürfel pro 24 Stunden','45 Würfel je Zyklus in 8 bis 18 Minuten','28,4 l Vorratsbehälter (ca. 15 kg Eis) mit Sichtfenster','Wählbare Eiswürfelgröße über LED-Display','Automatische Selbstreinigungsfunktion','Einstellbarer Timer für die Eisproduktion','Fester Wasseranschluss mit Zu- und Ablaufschlauch im Lieferumfang','Edelstahlgehäuse, geschmacks- und geruchsneutrale Materialien im Eiskontakt','Kältemittel R290, 370 W Leistung','Höhenverstellbare Standfüße']::text[],
 rental_notes=ARRAY['Für den Dauerbetrieb wird ein Wasseranschluss sowie ein Ablauf benötigt; Zu- und Ablaufschlauch sind im Lieferumfang enthalten.','Abmessungen 80 x 40 x 50 cm (H x B x T), Gewicht 25,5 kg – Transport stehend, zu zweit heben.','Rückgabe entleert und grob gereinigt.']::text[],
 weight_kg=25.5,
 on_request=true,
 seo_title='Eiswürfelmaschine mieten Krefeld – 45 kg/Tag Gastro | SLT',
 seo_meta_description='Profi-Eiswürfelmaschine mieten in Krefeld & Bonn: 45 kg Eis pro 24 h, 28,4 l Vorratsbehälter, Edelstahl, Selbstreinigung. Für Gastronomie, Catering & Events.',
 seo_faqs='[{"question":"Wie viel Eis produziert die Profi-Eiswürfelmaschine pro Tag?","answer":"Bis zu 45 kg Eiswürfel in 24 Stunden. Pro Zyklus entstehen 45 Würfel in 8 bis 18 Minuten – genug für Bars, Restaurants, Hotels und große Events."},{"question":"Wie groß ist der Vorratsbehälter?","answer":"Der Behälter fasst 28,4 Liter und damit rund 15 kg Eiswürfel. Über das Sichtfenster siehst du den Füllstand jederzeit."},{"question":"Braucht die Maschine einen Wasseranschluss?","answer":"Ja. Das Gerät arbeitet mit einem industriellen Pumpenkreislauf und festem Wasseranschluss. Zu- und Ablaufschlauch sind im Lieferumfang enthalten; am Aufstellort werden Wasseranschluss und Ablauf benötigt."},{"question":"Welche Abmessungen und welches Gewicht hat das Gerät?","answer":"80 x 40 x 50 cm (H x B x T) bei 25,5 kg Eigengewicht. Das Netzkabel ist 1,8 m lang, die Standfüße sind höhenverstellbar."},{"question":"Welche Stromversorgung wird benötigt?","answer":"220–240 V bei 50/60 Hz über eine normale Schuko-Steckdose. Die Kompressorleistung beträgt 370 W, als Kältemittel kommt R290 zum Einsatz."},{"question":"Muss ich die Maschine manuell reinigen?","answer":"Das Gerät hat eine automatische Selbstreinigungsfunktion. Zurückgegeben wird die Maschine entleert und grob gereinigt."},{"question":"An welchen Standorten ist die Maschine verfügbar?","answer":"An den Standorten Krefeld und Bonn. Die Vermietung läuft auf Anfrage – wir prüfen Verfügbarkeit und Bereitstellung für deinen Zeitraum kurzfristig."}]'::jsonb,
 seo_draft_meta_description=NULL, seo_draft_faqs=NULL, seo_draft_generated_at=NULL,
 seo_use_case_bau='Kaltgetränke-Versorgung für Richtfeste, Baustellenübergaben und Mitarbeiterfeste – ein Gerät deckt den Eisbedarf eines ganzen Veranstaltungstages.',
 seo_use_case_event='Hochzeiten, Firmenfeiern, Sommerfeste, Cateringbetriebe, Bars, Restaurants, Cafés und Hotels. 45 Würfel je Zyklus versorgen mehrere Cocktail-Stationen gleichzeitig.',
 seo_use_case_privat='Große Gartenpartys, Familienfeiern und Vereinsfeste, bei denen kompakte Tischgeräte nicht mehr ausreichen.',
 updated_at=now()
WHERE id='bb834ca6-95ac-4f99-b716-99a91eb541ed';