UPDATE public.b2b_managed_products SET
 name = 'Profi-Schwenkgrill Ø 120 cm',
 model_name = 'Großer Schwenkgrill mit 120 cm Rost – für Vereinsfeste, Firmenfeiern & Catering',
 description = 'Profi-Schwenkgrill mit 120 cm Grillrost, Kurbelzug und Feuerschale – für große Gruppen. Ab 90 € pro Tag, in Krefeld dauerhaft im Bestand.',
 detailed_description = 'Der Profi-Schwenkgrill mit 120 cm Rostdurchmesser ist unser größter Holzkohlegrill zum Mieten – gebaut für Vereinsfeste, Schützenfeste, Firmenfeiern, Hochzeiten und Catering, wo viele Portionen gleichzeitig vom Rost müssen. Rund 1,1 m² Grillfläche bieten Platz für Bratwürste, Steaks, Spieße und Gemüse in einem Durchgang.

Der runde Rost hängt an Ketten in einem stabilen Stahlgestell und wird über eine Handkurbel mit Seilzug stufenlos in der Höhe verstellt. So regelst du die Hitze über den Abstand zur Glut, statt Kohle nachschieben zu müssen – vom scharfen Angrillen bis zum Warmhalten. Der Rost lässt sich seitlich ausschwenken, um Glut nachzulegen oder das Grillgut bequem abzunehmen. Befeuert wird die Feuerschale mit Holzkohle, Briketts oder Holz.

Das Gerät ist rund 2,20 m hoch und wird für den Transport liegend verladen – ein Transporter oder Anhänger ist erforderlich. Wer selbst kein passendes Fahrzeug hat, mietet bei uns optional direkt einen passenden Anhänger zum Ankoppeln mit dazu; alternativ liefern wir den Grill an (Lieferkosten-Tarif A). Am Hauptsitz Krefeld ist der Schwenkgrill dauerhaft im Bestand, für Bonn und Mülheim an der Ruhr disponieren wir ihn aus Krefeld.',
 price_per_day = 'ab 90 €',
 images = ARRAY['/product-images/schwenkgrill-profi-120-1.jpeg','/product-images/schwenkgrill-profi-120-2.jpeg'],
 image_alts = ARRAY['Profi-Schwenkgrill Ø 120 cm mieten – Edelstahl-Feuerschale mit rundem Grillrost am Kettenzug','Schwenkgrill mieten – Gestell mit Handkurbel und Kette zur stufenlosen Höhenverstellung des 120-cm-Rostes'],
 specifications = '{"Bauart":"Schwenkgrill mit Gestell, Kettenaufhängung und Handkurbel","Rostdurchmesser":"120 cm","Grillfläche":"ca. 1,1 m²","Höhe":"ca. 2,20 m","Höhenverstellung":"Stufenlos über Kurbel/Seilzug","Befeuerung":"Holzkohle, Briketts oder Holz","Material":"Stahl / Edelstahl","Transport":"Liegend transportierbar – passender Anhänger optional mietbar","Aufstellort":"Nur im Freien, auf festem, nicht brennbarem Untergrund","Standort":"Krefeld dauerhaft im Bestand; Bonn und Mülheim an der Ruhr auf Anfrage"}'::jsonb,
 features = ARRAY['120 cm Rostdurchmesser – ca. 1,1 m² Grillfläche für große Gruppen','Stufenlose Höhenverstellung per Handkurbel statt Kohleschieben','Rost ausschwenkbar zum Nachlegen und Abnehmen','Befeuerung wahlweise mit Holzkohle, Briketts oder Holz','Liegend transportierbar – optional mit passendem Anhänger','Lieferung nach Lieferkosten-Tarif A (Sprinter Standard) möglich'],
 rental_notes = ARRAY['Holzkohle, Briketts, Anzünder und Grillbesteck sind nicht im Mietpreis enthalten.','Richtwert Holzkohle: Für den 120-cm-Rost sind rund 6–8 kg Grundfüllung realistisch, plus Nachschub bei längerer Grilldauer. Briketts halten die Glut länger, stückige Holzkohle wird schneller heiß.','Betrieb ausschließlich im Freien, mit Abstand zu Gebäuden, Zelten, Markisen und brennbarem Material.','Rückgabe grob gereinigt und ausgekühlt, Asche entfernt – sonst berechnen wir eine Reinigungspauschale.','Höhe ca. 2,20 m: Transport liegend, passender Anhänger optional mietbar.'],
 tags = ARRAY['event','catering','gastronomie','grill','hochzeit'],
 seo_title = 'Schwenkgrill mieten Krefeld – Profi Ø 120 cm | SLT',
 seo_meta_description = 'Profi-Schwenkgrill Ø 120 cm mieten in Krefeld: ca. 1,1 m² Grillfläche, Kurbel-Höhenverstellung, Holzkohle. Ab 90 € pro Tag – dauerhaft im Bestand.',
 seo_use_case_bau = 'Richtfest, Baustellenabschluss oder Sommerfest der Firma: Der Schwenkgrill braucht keinen Strom und arbeitet mit Holzkohle – ideal auf Betriebshöfen und Freiflächen ohne Anschluss.',
 seo_use_case_event = 'Vereinsfeste, Schützenfeste, Straßenfeste, Hochzeiten und Catering: ca. 1,1 m² Grillfläche halten den Nachschub für große Gruppen konstant.',
 seo_use_case_privat = 'Große Geburtstage, Nachbarschafts- und Gartenfeste: deutlich mehr Rostfläche als jeder Kugelgrill, mit stufenloser Hitzeregelung über die Kurbel.',
 seo_faqs = '[{"q":"Wie groß ist der Grillrost des Profi-Schwenkgrills?","a":"Der runde Rost hat 120 cm Durchmesser, das entspricht rund 1,1 m² Grillfläche. Damit lassen sich Bratwürste, Steaks, Spieße und Gemüse in einem Durchgang zubereiten."},{"q":"Wie viel Holzkohle brauche ich für den 120-cm-Schwenkgrill?","a":"Als Richtwert sind rund 6–8 kg Grundfüllung realistisch, bei mehrstündigem Betrieb kommt Nachschub dazu. Briketts halten die Glut länger, stückige Holzkohle wird schneller heiß. Der tatsächliche Verbrauch hängt von Grilldauer, Grillgut und Wetter ab – Kohle und Anzünder sind nicht im Mietpreis enthalten."},{"q":"Wie wird die Hitze reguliert?","a":"Über die Handkurbel mit Seilzug wird der Rost stufenlos in der Höhe verstellt. Du regelst die Hitze also über den Abstand zur Glut – vom scharfen Angrillen bis zum Warmhalten. Zusätzlich lässt sich der Rost seitlich ausschwenken."},{"q":"Wie transportiere ich den Schwenkgrill?","a":"Der Grill ist rund 2,20 m hoch und wird liegend transportiert. Ein Transporter oder Anhänger ist nötig – einen passenden Anhänger zum Ankoppeln kannst du bei uns optional mitmieten."},{"q":"Was kostet die Lieferung des Schwenkgrills?","a":"Die Lieferung erfolgt nach Tarif A (Sprinter Standard) unseres Lieferkostenrechners – wie bei unserem übrigen Eventbedarf. Den genauen Preis für deine Entfernung berechnest du direkt im Lieferkostenrechner."},{"q":"Ist der Schwenkgrill in Krefeld dauerhaft verfügbar?","a":"Ja, am Hauptsitz Krefeld ist der Profi-Schwenkgrill dauerhaft im Bestand. Für deinen Wunschtermin bestätigen wir die Verfügbarkeit kurzfristig über das Anfrageformular oder telefonisch."},{"q":"Was kostet die Miete pro Tag?","a":"Die Miete startet ab 90 € netto pro Tag. Für Wochenend- und Mehrtagespauschalen erhältst du auf Anfrage ein individuelles Angebot."},{"q":"Wie muss der Schwenkgrill zurückgegeben werden?","a":"Ausgekühlt, grob gereinigt und mit entfernter Asche. Andernfalls berechnen wir eine Reinigungspauschale."}]'::jsonb,
 updated_at = now()
WHERE slug = 'schwenkgrill-profi-120';