UPDATE public.b2b_managed_products SET
  model_name = 'Kompakt-Modell 12 kg/24 h, Bullet-Eis – ideal für Bar, Hausbar & Feiern',
  description = 'Kompakte Eiswürfelmaschine mit bis zu 12 kg Eis pro Tag. Vollautomatisch, mit 3,2-l-Wassertank – kein Wasseranschluss nötig. Erste Eiswürfel nach wenigen Minuten.',
  detailed_description = 'Kompakter SLT Eiswürfelbereiter zum Mieten – die praktische Eiswürfelmaschine für Hochzeiten, Firmenfeiern, Gartenpartys, Foodtrucks, Messestände und den privaten Haushalt. Das freistehende Edelstahl-Tischgerät produziert bis zu 12 kg Bullet-Eis pro 24 Stunden – 14 Eiskugeln pro Zyklus – vollautomatisch aus dem integrierten 3,2-Liter-Wassertank, ohne festen Wasseranschluss. So lässt es sich flexibel überall dort aufstellen, wo Strom vorhanden ist – auf der Theke, im Cateringzelt oder im Getränkeausschank.

Die Bedienung erfolgt über ein Touch-Bedienfeld mit LED-Display: Wasser einfüllen, Eisgröße wählen, starten – nach wenigen Minuten sind die ersten Eiswürfel fertig. Ein Alarmsignal meldet vollen Eisbehälter oder niedrigen Wasserstand. Der leistungsstarke, geräuscharme Kompressor arbeitet mit dem Kältemittel R290 und produziert ohne Vorkühlzeit durchgehend. Das Sichtfenster im Deckel zeigt jederzeit den Füllstand, der entnehmbare Vorratsbehälter (1,8 kg) erleichtert Entnahme, Umfüllen in einen Getränkekühler und Reinigung.

Das Gerät ist an unserem Hauptsitz Krefeld und an unserer Filiale Bonn direkt buchbar. Für Mülheim an der Ruhr disponieren wir es kurzfristig aus dem Hauptsitz Krefeld.',
  images = ARRAY['/product-images/geschirr/slt-eiswuerfelbereiter-1.jpeg','/product-images/geschirr/slt-eiswuerfelbereiter-2.jpeg','/product-images/geschirr/slt-eiswuerfelbereiter-3.jpeg'],
  image_alts = ARRAY['SLT Eiswürfelbereiter kompakt mieten – Edelstahl-Eiswürfelmaschine mit Sichtfenster','SLT Eiswürfelbereiter kompakt – Abmessungen 31 x 43 x 40 cm','Entnehmbarer Eisvorratsbehälter mit Bullet-Eis und Eisschaufel'],
  specifications = '{"Geräteart":"Freistehende Eiswürfelmaschine (Ice Maker), Tischgerät","Eisproduktion":"ca. 12 kg / 24 h, 14 Eiskugeln pro Zyklus (Bullet-Eis)","Wassertank":"3,2 Liter, manuelles Nachfüllen","Eisvorratsbehälter":"1,8 kg, entnehmbar","Gehäuse":"Edelstahl, Silber – Deckel mit Sichtfenster","Abmessungen (B×H×T)":"ca. 31 × 43 × 40 cm","Gewicht":"ca. 12,5 kg","Stromversorgung":"220–240 V~ / 50–60 Hz (Schuko-Steckdose)","Kältemittel":"R290","Bedienung":"Touch-Bedienfeld mit LED-Display, Alarm bei vollem Behälter / niedrigem Wasserstand","Netzkabel":"ca. 130 cm","Aufstellort":"Bar-/Küchentheke, Cateringzelt, Foodtruck, Büro, Hausbar"}'::jsonb,
  features = ARRAY['Bis zu 12 kg Bullet-Eis pro 24 Stunden','3,2-l-Wassertank – kein Festwasseranschluss nötig','Erste Eiswürfel nach wenigen Minuten','Touch-Bedienfeld mit LED-Display und Eisgrößenwahl','Alarmsignal bei vollem Eisbehälter / niedrigem Wasserstand','Entnehmbarer 1,8-kg-Vorratsbehälter, einfach zu reinigen'],
  weight_kg = 12.5,
  seo_title = 'Eiswürfelmaschine mieten – 12 kg/24 h kompakt | SLT Rental',
  seo_meta_description = 'Kompakte Eiswürfelmaschine mieten: 12 kg Eis/24 h, 3,2-l-Tank, ohne Wasseranschluss. Direkt buchbar in Krefeld & Bonn, Mülheim an der Ruhr aus Krefeld geliefert.',
  seo_use_case_bau = 'Kühle Getränke bei Richtfest, Baustellenübergabe oder Firmenfeier – überall, wo ein Stromanschluss vorhanden ist.',
  seo_use_case_event = 'Hochzeiten, Firmenfeiern, Sommerfeste, Foodtrucks, Messeauftritte, Barbetrieb und Cateringzelte – bis zu 12 kg Bullet-Eis pro Tag für Cocktails, Longdrinks, Softdrinks und Sekt-Kübel.',
  seo_use_case_privat = 'Gartenparty, Geburtstag, Grillabend, Silvester oder Hausbar – frische Eiswürfel ohne verstopftes Gefrierfach oder Plastikbeutel.',
  seo_faqs = '[{"q":"Wird ein fester Wasseranschluss benötigt?","a":"Nein. Der SLT Eiswürfelbereiter arbeitet mit einem integrierten 3,2-Liter-Wassertank, den Sie manuell mit Leitungswasser befüllen. Sie brauchen nur eine Schuko-Steckdose (220–240 V) am Aufstellort."},{"q":"Wie viel Eis produziert die Eiswürfelmaschine pro Tag?","a":"Bis zu 12 kg Bullet-Eis in 24 Stunden. Pro Zyklus entstehen 14 Eiskugeln, die im entnehmbaren Vorratsbehälter mit 1,8 kg Fassungsvermögen landen. Die tatsächliche Menge hängt von Umgebungstemperatur und gewählter Eisgröße ab."},{"q":"Wie lange dauert es, bis die ersten Eiswürfel fertig sind?","a":"Nach dem Einschalten sind die ersten Eiswürfel innerhalb weniger Minuten fertig. Danach produziert der Kompressor (Kältemittel R290) ohne Vorkühlzeit durchgehend weiter, solange Wasser im Tank ist und der Behälter nicht voll ist."},{"q":"Wie groß und schwer ist das Gerät?","a":"Das Tischgerät misst ca. 31 × 43 × 40 cm (B×H×T) und wiegt rund 12,5 kg. Das Netzkabel ist ca. 130 cm lang. Es passt damit auf jede Theke, Küchenarbeitsplatte oder Cateringstation."},{"q":"Für welche Einsatzorte ist der Eiswürfelbereiter geeignet?","a":"Innenräume, überdachte Außenbereiche, Cateringzelte, Foodtrucks, Hausbar, Büro oder Vereinsheim. Wichtig ist ein trockener, ebener Aufstellort mit Stromanschluss und ausreichend Belüftung, da das Gerät seitlich warme Abluft abgibt."},{"q":"Wie muss das Gerät zurückgegeben werden?","a":"Bitte geben Sie den Eiswürfelbereiter gereinigt und mit vollständig entleertem Wassertank zurück. Innenraum und Vorratsbehälter einfach mit klarem Wasser ausspülen und trocken wischen. Bei stark verschmutzter Rückgabe berechnen wir eine Reinigungspauschale."},{"q":"Ist der SLT Eiswürfelbereiter an allen drei Standorten verfügbar?","a":"Ja. An unserem Hauptsitz Krefeld und an unserer Filiale Bonn ist das Gerät direkt buchbar. Für Mülheim an der Ruhr disponieren wir es kurzfristig aus dem Hauptsitz Krefeld – in der Regel innerhalb von 24 Stunden."}]'::jsonb,
  updated_at = now()
WHERE slug = 'slt-eiswuerfelbereiter';